---
abstract: "fill HTML form elements' values."
author:
  - "Zoffix <'zoffix@cpan.org'>"
build_requires:
  Test::More: 0
  perl: 5.006
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4007, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-ZofCMS-Plugin-FormFiller
provides:
  App::ZofCMS::Plugin::FormFiller:
    file: lib/App/ZofCMS/Plugin/FormFiller.pm
    version: 0.0103
resources:
  license: http://dev.perl.org/licenses/
version: 0.0103
